FROM docker

RUN  wget https://github.com/yudai/gotty/releases/download/v2.0.0-alpha.3/gotty_2.0.0-alpha.3_linux_386.tar.gz && \
     tar -zxvf /gotty_2.0.0-alpha.3_linux_386.tar.gz && \
     rm /gotty_2.0.0-alpha.3_linux_386.tar.gz